### ISSUE TITLE
run in docker panic

### ISSUE THREAD

**Issue by hellojukay** [pivotal-cf/fluent-bit-out-syslog#13]
`fluent-bit    | panic: runtime error: invalid memory address or nil pointer dereference
fluent-bit    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2b5820a4aa39]
fluent-bit    |
fluent-bit    | goroutine 17 [running, locked to thread]:
fluent-bit    | github.com/pivotal-cf/fluent-bit-out-syslog/pkg/syslog.(*Out).Write(0x0, 0xc420010630, 0x35734fa6, 0xed3105e5a, 0x2b5821037500, 0xc4200160b0, 0x9, 0xc420000600, 0xc420052000)
fluent-bit    | 	/home/infra/go/src/github.com/pivotal-cf/fluent-bit-out-syslog/pkg/syslog/out.go:81 +0xa9
fluent-bit    | main.FLBPluginFlush(0x2b5824e00000, 0xc4001fd510, 0x2b582022fb60, 0xc400000008)
fluent-bit    | 	/home/infra/go/src/github.com/pivotal-cf/fluent-bit-out-syslog/cmd/main.go:62 +0x108
fluent-bit    | main._cgoexpwrap_522c5543b4e9_FLBPluginFlush(0x2b5824e00000, 0x3a37463a001fd510, 0x2b582022fb60, 0x22646e617262222c)
fluent-bit    | 	github.com/pivotal-cf/fluent-bit-out-syslog/cmd/_obj/_cgo_gotypes.go:82 +0x3f
fluent-bit exited with code 2`

**Comment by hellojukay** [comment]
i think the fluent-bit config  looks like this
`[OUTPUT]
    Name syslog
    Addr dev.snc.360es.cn:514
    Enable_TLS  false
    Insecure_Skip_Verify  true
    sinks [{"addr":"dev.snc.360es.cn:514","namespace":"commander","tls":{"insecure_skip_verify":false}}]`

**Comment by dennyzhang** [comment]
@hellojukay , the error handling shall need some improvement.

And more importantly, is the port 514 UDP or TCP?

**Comment by hellojukay** [comment]
@dennyzhang The port is 514  TCP

**Comment by dennyzhang** [comment]
PR WIP: https://github.com/pivotal-cf/fluent-bit-out-syslog/pull/14

**Comment by hellojukay** [comment]
@dennyzhang ok, it works.
