### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by prashantvicky** [pivotal-cf/fluent-bit-out-syslog#16]
Whne i am using your plugin to flush data to syslog server its get stuck see below.
 ./fluent-bit --input cpu --plugin ./out_syslog.so --config fluentbit-config.conf
Fluent-Bit v0.13.8
Copyright (C) Treasure Data

[2018/08/29 10:23:42] [ info] [engine] started (pid=26180)
2018/08/29 10:23:42 [out_syslog] sinks =  [{"addr":"localhost:514", "enable_tls":"true", "insecure_skip_verify":"true"}]

**Comment by ahevenor** [comment]
This all looks ok to us. Are you still stuck? There is a docker image you can use on [dockerhub](https://hub.docker.com/r/oratos/fluent-bit-out-syslog/).

**Comment by ahevenor** [comment]
Closing issue.
