### ISSUE TITLE
FluentBit does not retain logs as expected

### ISSUE THREAD

**Issue by RaulGracia** [pivotal-cf/fluent-bit-out-syslog#22]
**Problem description**

We have found the following problem with logs in the `fluentbit` service that comes by default in PKS clusters using the `syslog` output plugin:

1) We execute a test pod that produces logs that are captured by `fluentbit`.
2) The first rotation of the a log for that test pod seems correct, despite the pod generated 123MB in less than 1 minute (clearly excessive, but good for testing this issue).
3) After rotating the first log, the second one started growing, but it is also _reduced its size_. By some reason, `fluentbit` is not properly rotating it, but apparently just overwriting it. By some reason, it only stores the last 2 rotated logs, despite nothing in the configuration seems to define such a limitation.
4) We have reproduced the experiment by updating the image version of `fluentbit` in one PKS cluster to the latest one (`v0.17`), and of course this also happens with the version that comes by default in PKS (`v0.11` and `v0.12`). In all cases we observed the same results.

From inside the `fluentbit` pod, we can see that:
1) The second rotation for the log `xxx-json.log` is growing in size (99MB).
```
root@fluent-bit-ffw5m:/var/vcap/store/docker/docker/containers/f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9# ls -lah
total 221M
drwx------  4 root root 4.0K Mar 15 19:51 .
drwx------ 16 root root 4.0K Mar 15 19:50 ..
drwx------  2 root root 4.0K Mar 15 19:46 checkpoints
-rw-------  1 root root 7.0K Mar 15 19:46 config.v2.json
-rw-r-----  1 root root  99M Mar 15 19:52 f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9-json.log
-rw-r-----  1 root root 123M Mar 15 19:51 f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9-json.log.1
-rw-r--r--  1 root root 2.2K Mar 15 19:46 hostconfig.json
drwx------  2 root root 4.0K Mar 15 19:46 mounts
```
2) Then, it reduces its size (41MB):
```
root@fluent-bit-ffw5m:/var/vcap/store/docker/docker/containers/f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9# ls -lah
total 163M
drwx------  4 root root 4.0K Mar 15 19:52 .
drwx------ 16 root root 4.0K Mar 15 19:50 ..
drwx------  2 root root 4.0K Mar 15 19:46 checkpoints
-rw-------  1 root root 7.0K Mar 15 19:46 config.v2.json
-rw-r-----  1 root root  41M Mar 15 19:52 f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9-json.log
-rw-r-----  1 root root 123M Mar 15 19:52 f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9-json.log.1
-rw-r--r--  1 root root 2.2K Mar 15 19:46 hostconfig.json
drwx------  2 root root 4.0K Mar 15 19:46 mounts
```

3) Then, it grows again (90MB), which indicates that is being continuously overwritten:
```
root@fluent-bit-ffw5m:/var/vcap/store/docker/docker/containers/f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9# ls -lah
total 212M
drwx------  4 root root 4.0K Mar 15 19:52 .
drwx------ 16 root root 4.0K Mar 15 19:50 ..
drwx------  2 root root 4.0K Mar 15 19:46 checkpoints
-rw-------  1 root root 7.0K Mar 15 19:46 config.v2.json
-rw-r-----  1 root root  90M Mar 15 19:52 f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9-json.log
-rw-r-----  1 root root 123M Mar 15 19:52 f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9-json.log.1
-rw-r--r--  1 root root 2.2K Mar 15 19:46 hostconfig.json
drwx------  2 root root 4.0K Mar 15 19:46 mounts
```

Do you have any ideas if there is any problem with `fluentbit` version being used in PKS cluster or its configuration?

**Information for issue reproduction**
This is the configuration of `fluentbit` pod (various files).
```
root@fluent-bit-22sj5:/fluent-bit/etc# cat filter-kubernetes.conf
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_URL            https://kubernetes.default.svc.cluster.local:443
    Merge_Log           On
    K8S-Logging.Parser  On
    
    
root@fluent-bit-22sj5:/fluent-bit/etc# cat filters.conf
@INCLUDE filter-kubernetes.conf


root@fluent-bit-22sj5:/fluent-bit/etc# cat fluent-bit.conf
[SERVICE]
    Flush         1
    Log_Level     info
    Daemon        off
    Parsers_File  parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

@INCLUDE inputs.conf
@INCLUDE filters.conf
@INCLUDE outputs.conf


root@fluent-bit-22sj5:/fluent-bit/etc# cat input-forward.conf
[INPUT]
    Name forward
    Port 24225
    Listen localhost
    

root@fluent-bit-22sj5:/fluent-bit/etc# cat input-kubernetes.conf
[INPUT]
    Name              tail
    Tag               kube.*
    Path              /var/log/containers/*.log
    Parser            docker
    DB                /var/log/flb_kube.db
    Mem_Buf_Limit     5MB
    Skip_Long_Lines   On
    Refresh_Interval  10
    

root@fluent-bit-22sj5:/fluent-bit/etc# cat inputs.conf
@INCLUDE input-kubernetes.conf
@INCLUDE input-forward.conf


root@fluent-bit-22sj5:/fluent-bit/etc# cat output-file.conf
[OUTPUT]
    Name file
    Match *
    Path /tmp/output.txt
    

root@fluent-bit-22sj5:/fluent-bit/etc# cat output-null.conf
[OUTPUT]
    Name null
    
    
root@fluent-bit-22sj5:/fluent-bit/etc# cat output-syslog.conf
[OUTPUT]
    Name syslog
    Match *
    Sinks [{\"addr\":\"example.com:12345\"}]
    
    
root@fluent-bit-22sj5:/fluent-bit/etc# cat outputs.conf
@INCLUDE output-null.conf


root@fluent-bit-22sj5:/fluent-bit/etc# cat parsers.conf
[PARSER]
    Name   json
    Format json
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z

[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
    Time_Keep   On
    # Command      |  Decoder | Field | Optional Action
    # =============|==================|=================
    Decode_Field_As   escaped    log
```
Some info of a `fluentbit` pod used:
```
Name:               fluent-bit-hjfzj
Namespace:          pks-system
...
Controlled By:      DaemonSet/fluent-bit
Init Containers:
  concat-keystore:
    Container ID:  docker://ed78298ddb59b6e92c3955d3031d8770c6a6b9611de984347d2a53e6c6391570
    Image:         oratos/fluent-bit-out-syslog:v0.11
...
ghostunnel:
    Container ID:  docker://1ce3b8998900c5ae0277b3c3964ac23c132293dbe93b3255f72db54273bc4fd1
    Image:         oratos/ghostunnel:v0.12
```

**Comment by hev** [comment]
@RaulGracia Thanks for your submission. We have seen various issues related to long log files but have had trouble pinning them down. We will look more directly into your use case to see if we can identify a root cause.

**Comment by RaulGracia** [comment]
Thanks @hev, we are intensively using PKS clusters in our project ([Pravega](https://github.com/pravega/pravega) by DellEMC). At this point, it is quite important for the development team to get all the logs to debug any potential issue. If there is any bugfix release/version you want us to try in our environment, please let me know.

**Comment by RaulGracia** [comment]
Hi @hev, is there any progress on finding the root cause for this issue? Any piece of news on the progress of this issue is more than welcome.

**Comment by wfernandes** [comment]
@RaulGracia We would like to get some clarification on the issue you are facing. 

> Are you seeing log loss or repeated logs in your configured syslog output?

I think there is a misunderstanding on log-rotation here. **Fluent Bit is not responsible for rotating logs**. Fluent Bit is configured (by default) to tail logs within the `/var/log/containers/*.log`. These log files are actually a series of symlinks to `f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9-json.log` and **not** the rotated log file `f0b596d30ef4290f4cc2ae006bd7ab47a98194804ae6449a1dae9aaa2e6cf4d9-json.log.1`.

cc @Benjamintf1

**Comment by RaulGracia** [comment]
@wfernandes thanks a lot for your input. If I understood your comment correctly, I think that what is happening is the following:

1) In our PKS clusters, pod containers are using some default [logging options](https://docs.docker.com/v17.09/engine/admin/logging/json-file/#options) (e.g., `--log-opt`). This is what dictates the rotation behavior of logs going through `stdout` and `stderr` in a container.

2) If the default is 1 rotated log, then the overwrite behavior is expected and this is the behavior that we are observing in fluentbit.

3) Unfortunately, it looks like we cannot easily change such `--log-opt` defaults without having to restart the Docker daemon used by Kubernetes, which is not ideal (cc/ @adrianmo). 

If there is no other alternative, it looks like the most practical approach long term will be to export logs to an external system (e.g., logstash) instead of relying on collecting the syslog files for all the containers.

**Comment by wfernandes** [comment]
@RaulGracia Yes. PKS/CFCR configures the docker driver to rotate the log files, and it is not trivial to change.

https://github.com/cloudfoundry-incubator/kubo-deployment/blob/98b6371c0ba26a942d5ab5d4449fe74e2fc740ee/manifests/cfcr.yml#L339-L341

We ingress the docker logs using the [`tail` plugin](https://fluentbit.io/documentation/0.14/input/tail.html) and egress them via tcp to a syslog destination.
If you are seeing some log loss then it **may** help to configure the `fluent-bit` configmap in the `pks-system` namespace with a higher `Mem_Buf_Limit` and shorter `Refresh_Interval` which are ingress properties on the `tail` plugin.

**Comment by hev** [comment]
@RaulGracia what rate of logs are you producing? CFCR would be more likely to change log rotation behavior if we have a sense of how likely this scenario is. I'd also like to document it.

**Comment by RaulGracia** [comment]
@hev as part of our continuous integration cycle we execute a battery of distributed tests in our project (where syslog plugin is mainly used). All the logs from all services instances created and tests occupy 40GB approx of raw text (in `DEBUG` log level), and these logs are generated in 2.5hrs. Hope this helps!

**Comment by amaheshwari21** [comment]
@RaulGracia @hev did you get any fix for this problem? we are hitting the same issue with fluent-bit and docker log rotation.

**Comment by debu99** [comment]
same issue found
