### ISSUE TITLE
Got messy code 

### ISSUE THREAD

**Issue by YanzhaoLi** [pivotal-cf/fluent-bit-out-syslog#29]
Setting the plugin's endpoint to a syslog server, the server could receive data but the data were just messy code.
Any advice?

**Comment by jenting** [comment]
@YanzhaoLi Could you please provided more information on the syslog server? Could the syslog server process RFC5424 format? Is the data all messy just part of messy?

**Comment by YanzhaoLi** [comment]
@jenting I use LogInsight as the syslog server.  All the data are messy.

**Comment by pianohacker** [comment]
@YanzhaoLi Could you please give an example output, or screenshot?

**Comment by YanzhaoLi** [comment]
@pianohacker  @jenting I misconfigured the TLSconfig, causing sending error message which is messy code to endpoint.
